# Generated by Django 5.2.8 on 2025-11-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_thumbnail_recipe_thumbnail_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='calories',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='common',
            field=models.BooleanField(default=False),
        ),
    ]
