# Generated by Django 5.2.8 on 2025-11-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredient_calories_ingredient_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='thumbnail_mime_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='thumbnail_source_url',
        ),
        migrations.CreateModel(
            name='RecipeThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_obj', to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipe_thumbnail',
            },
        ),
    ]
