# Generated by Django 5.2.8 on 2025-12-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_thumbnail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_yet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recipes.userstock')),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['user', 'read_yet'], name='notificatio_user_id_1cb267_idx')],
            },
        ),
    ]
