# Generated by Django 5.2.8 on 2026-01-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='required_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
